<?php

return [
    'profile' => [
        'name' => 'El Hadji Ahmadou CHERIF DIOUF',
        'role' => 'Ingénieur Full-Stack & Formateur',
        'location' => 'Dakar, Keur Massar (Ouvert au Remote)',
        'email' => 'el.hadji.ahmadou.cherif.diouf@gmail.com',
        'phone' => '+221 78 517 11 17',
        'linkedin' => 'linkedin.com/in/cherif-diouf-9b41b8288',
        'github' => 'github.com/Maximus203',
        'avatar' => '/assets/photo.webp',
        'bioShort' => 'Développeur passionné par la création d\'applications web modernes et performantes. Expert Laravel, React et DevOps, je me spécialise dans l\'architecture full-stack et la formation technique.',
    ],

    'experience' => [
        [
            'id' => 1,
            'company' => 'KASA',
            'role' => 'Consultant IT & Développeur Full-Stack',
            'period' => '2024 - Présent',
            'description' => [
                'Développement d\'une API REST avec Laravel pour la gestion de cliniques et pharmacies',
                'Création d\'interfaces utilisateurs modernes avec React & TailwindCSS',
                'Mise en place d\'une architecture sécurisée avec authentification JWT',
                'Optimisation des performances et mise en production sur serveur Linux',
            ],
        ],
        [
            'id' => 2,
            'company' => 'Edacy (Freelance)',
            'role' => 'Formateur Développement Web',
            'period' => '2023 - 2024',
            'description' => [
                'Formation de 30+ étudiants sur Laravel, React et Git',
                'Conception de supports pédagogiques interactifs et projets pratiques',
                'Accompagnement personnalisé sur des projets réels',
                'Taux de satisfaction de 95%',
            ],
        ],
        [
            'id' => 3,
            'company' => 'ESTM',
            'role' => 'Formateur & Développeur',
            'period' => '2022 - 2023',
            'description' => [
                'Enseignement des fondamentaux du web (HTML, CSS, JavaScript, PHP)',
                'Développement de projets académiques avec Laravel & Symfony',
                'Animation d\'ateliers pratiques sur Git, Docker et CI/CD',
                'Mentorat de projets de fin d\'études',
            ],
        ],
    ],

    'skills' => [
        [
            'name' => 'Frontend',
            'skills' => [
                ['name' => 'React', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg'],
                ['name' => 'TypeScript', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg'],
                ['name' => 'TailwindCSS', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg'],
                ['name' => 'Bootstrap', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg'],
            ],
        ],
        [
            'name' => 'Backend',
            'skills' => [
                ['name' => 'Laravel', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg'],
                ['name' => 'Symfony', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg'],
                ['name' => 'PHP', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg'],
                ['name' => 'Node.js', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg'],
            ],
        ],
        [
            'name' => 'DevOps & Tools',
            'skills' => [
                ['name' => 'Docker', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg'],
                ['name' => 'Git/GitHub', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg'],
                ['name' => 'CI/CD', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/githubactions/githubactions-original.svg'],
                ['name' => 'Linux', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg'],
            ],
        ],
        [
            'name' => 'Data',
            'skills' => [
                ['name' => 'MySQL', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg'],
                ['name' => 'PostgreSQL', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg'],
                ['name' => 'MongoDB', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg'],
                ['name' => 'SQLite', 'icon' => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg'],
            ],
        ],
    ],

    'education' => [
        [
            'id' => 1,
            'degree' => 'Licence en Informatique de Gestion',
            'school' => 'École Supérieure de Technologie et de Management (ESTM)',
            'period' => '2020 - 2023',
            'description' => 'Spécialisation en développement web et génie logiciel',
        ],
        [
            'id' => 2,
            'degree' => 'Baccalauréat Série S2',
            'school' => 'Lycée Limamou Laye',
            'period' => '2019 - 2020',
            'description' => 'Mention Assez Bien',
        ],
    ],

    'labels' => [
        'home' => 'Accueil',
        'gallery' => 'Galerie',
        'tools' => 'Outils',
        'about' => 'À Propos',
        'experience' => 'Expériences',
        'projects' => 'Projets',
        'skills' => 'Compétences',
        'education' => 'Formation',
        'available' => 'Disponible pour nouveaux projets',
        'role' => 'Développeur',
        'and' => '&',
        'mentor' => 'Formateur',
        'download' => 'Télécharger',
        'resume' => 'CV',
        'base' => 'Base',
        'status' => 'Statut',
        'selectedProjects' => 'Projets sélectionnés',
        'technicalSkills' => 'Compétences techniques',
        'workExperience' => 'Expériences professionnelles',
        'educationTitle' => 'Formation académique',
        'searchPlaceholder' => 'Rechercher un projet...',
        'startProject' => 'Démarrer un projet',
        'submitProjectTitle' => 'Parlons de votre projet',
        'submitProjectDesc' => 'Remplissez le formulaire ci-dessous et je vous répondrai rapidement.',
        'firstName' => 'Prénom',
        'lastName' => 'Nom',
        'email' => 'Email',
        'projectDetails' => 'Détails du projet',
        'attachFile' => 'Joindre un fichier',
        'filePlaceholder' => 'Glissez un fichier ou cliquez',
        'send' => 'Envoyer la demande',
        'cancel' => 'Annuler',
        'successMessage' => 'Votre demande a été envoyée avec succès !',
        'footerQuote' => 'Développeur Full-stack créant des expériences web modernes.',
        'sections' => 'Sections',
        'pages' => 'Pages & outils',
        'connect' => 'Me suivre',
        'builtWith' => 'Construit avec',
        'rights' => 'Tous droits réservés.',
        'allProjects' => 'Tous les projets',
        'toolReadme' => 'Readme generator',
        'toolMeme' => 'Meme generator',
        'toolConverter' => 'Image converter',
        'toolReadmeDesc' => 'Générez des fichiers README professionnels pour vos projets GitHub en quelques clics',
        'toolMemeDesc' => 'Créez des memes personnalisés avec vos images et textes favoris',
        'toolConverterDesc' => 'Convertissez vos images dans différents formats (JPG, PNG, WEBP)',
        'launch' => 'Lancer',
        'seoHomeTitle' => 'Cherif Diouf | Ingénieur Full-Stack & Formateur',
        'seoHomeDesc' => 'Portfolio de Cherif Diouf. Expert Laravel, React & DevOps. Découvrez mes projets, compétences et parcours.',
        'galleryTitle' => 'Galerie',
        'gallerySubtitle' => 'Moments marquants de mon parcours : conférences, meetups et événements tech',
        'toolsTitle' => 'Outils',
        'toolsSubtitle' => 'Collection d\'outils pratiques pour développeurs',
    ],
];
