import type { Language } from '@/types';

export const UI_LABELS: Record<Language, Record<string, string>> = {
  fr: {
    home: 'Accueil',
    gallery: 'Galerie',
    tools: 'Outils',
    about: 'À Propos',
    experience: 'Expériences',
    projects: 'Projets',
    skills: 'Compétences',
    education: 'Formation',
    available: 'Disponible pour nouveaux projets',
    role: 'Développeur',
    and: '&',
    mentor: 'Formateur',
    download: 'Télécharger',
    resume: 'CV',
    base: 'Base',
    status: 'Statut',
    top: 'Haut',
    selectedProjects: 'Projets sélectionnés',
    technicalSkills: 'Compétences techniques',
    workExperience: 'Expériences professionnelles',
    educationTitle: 'Formation académique',
    galleryTitle: 'Moments & événements',
    gallerySubtitle: 'Conférences, hackathons et vie communautaire.',
    toolsTitle: 'Boîte à outils',
    toolsSubtitle: 'Des utilitaires pratiques pour développeurs et créateurs.',
    toolReadme: 'Générateur readme',
    toolReadmeDesc: 'Créez le profil GitHub parfait avec des badges et stats dynamiques.',
    toolMeme: 'Générateur de meme',
    toolMemeDesc: 'Créez du contenu viral rapidement pour vos réseaux sociaux.',
    toolConverter: 'Convertisseur d\'images',
    toolConverterDesc: 'Optimisez vos assets : convertissez 1 image ou un lot de 10 simultanément.',
    launch: 'Lancer',
    searchPlaceholder: 'Rechercher un projet...',
    startProject: 'Proposer un projet',
    submitProjectTitle: 'Parlons de votre projet',
    submitProjectDesc: 'Remplissez le formulaire ci-dessous et je vous répondrai rapidement.',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    projectDetails: 'Détails du projet',
    attachFile: 'Joindre un fichier',
    filePlaceholder: 'Glissez un fichier ou cliquez',
    send: 'Envoyer la demande',
    cancel: 'Annuler',
    successMessage: 'Votre demande a été envoyée avec succès !',
    memeTopText: 'Texte du Haut',
    memeBottomText: 'Texte du Bas',
    memeUpload: 'Importer une image',
    memeDownload: 'Télécharger le Meme',
    memeFontSize: 'Taille du texte',
    memeTextColor: 'Couleur du texte',
    memeStrokeColor: 'Couleur du contour',
    memeDragDrop: 'Glissez une image ici',
    // Footer
    footerQuote: 'Développeur Full-stack créant des expériences web modernes.',
    sections: 'Sections',
    pages: 'Pages & outils',
    connect: 'Me suivre',
    builtWith: 'Construit avec',
    hostedOn: 'Hébergé sur',
    rights: 'Tous droits réservés.',
    allProjects: 'Tous les projets',
    // Students
    students: 'Étudiants',
    studentsTitle: 'Réalisations de mes étudiants',
    studentsSubtitle: 'Portfolios réalisés par mes étudiants durant leur formation.',
    studentsCount: 'portfolios mis en avant',
    studentsHighlight: 'Créés pendant leur parcours de formation',
    // SEO
    seoHomeTitle: "Cherif Diouf | Développeur Full-Stack, Digitalisation & Formateur – Dakar",
    seoHomeDesc: "Portfolio de El Hadji Ahmadou Cherif Diouf. Expert Laravel, React, Supabase & DevOps. Développement web/mobile, digitalisation d'entreprise, prompt engineering et formation au Sénégal.",
    seoGalleryTitle: "Galerie & Événements Tech | Cherif Diouf – Dakar, Sénégal",
    seoGalleryDesc: "Photos et moments des conférences, hackathons, graduations et événements tech au Sénégal. Cherif Diouf, développeur full-stack et formateur à Dakar.",
    seoToolsTitle: "Outils Gratuits pour Développeurs | Cherif Diouf",
    seoToolsDesc: "Outils open-source gratuits : Générateur de README GitHub, Convertisseur WebP, Créateur de Memes. Par Cherif Diouf, développeur full-stack au Sénégal.",
    seoStudentsTitle: "Réalisations de mes Étudiants | Cherif Diouf Formateur",
    seoStudentsDesc: "Portfolios web réalisés par les étudiants de Cherif Diouf durant leur formation en développement web à Dakar (ESTM, ISM, ESCOA).",
    // Profile switcher
    profileSoftware: 'Génie Logiciel',
    profileNetwork: 'Admin Réseaux',
    profileTeaching: 'Enseignement',
    viewProjects: 'Explorer mes réalisations',
    contactCta: 'Discutons ensemble',
    publications: 'Publications',
  },
  en: {
    home: 'Home',
    gallery: 'Gallery',
    tools: 'Tools',
    about: 'About',
    experience: 'Experience',
    projects: 'Projects',
    skills: 'Skills',
    education: 'Education',
    available: 'Available for new projects',
    role: 'Developer',
    and: '&',
    mentor: 'Mentor',
    download: 'Download',
    resume: 'Resume',
    base: 'Base',
    status: 'Status',
    top: 'Top',
    selectedProjects: 'Selected projects',
    technicalSkills: 'Technical skills',
    workExperience: 'Work experience',
    educationTitle: 'Education',
    galleryTitle: 'Moments & events',
    gallerySubtitle: 'Conferences, hackathons and community life.',
    toolsTitle: 'Dev toolbox',
    toolsSubtitle: 'Useful utilities for developers and creators.',
    toolReadme: 'Readme generator',
    toolReadmeDesc: 'Create the perfect GitHub profile with dynamic badges and stats.',
    toolMeme: 'Meme generator',
    toolMemeDesc: 'Create viral content quickly for your social media.',
    toolConverter: 'Image converter',
    toolConverterDesc: 'Optimize assets: convert 1 image or a batch of 10 simultaneously.',
    launch: 'Launch',
    searchPlaceholder: 'Search projects...',
    startProject: 'Propose a project',
    submitProjectTitle: "Let's discuss your project",
    submitProjectDesc: 'Fill out the form below and I will get back to you shortly.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    projectDetails: 'Project Details',
    attachFile: 'Attach File',
    filePlaceholder: 'Drag a file or click to upload',
    send: 'Send Request',
    cancel: 'Cancel',
    successMessage: 'Your request has been sent successfully!',
    memeTopText: 'Top Text',
    memeBottomText: 'Bottom Text',
    memeUpload: 'Upload Image',
    memeDownload: 'Download Meme',
    memeFontSize: 'Font Size',
    memeTextColor: 'Text Color',
    memeStrokeColor: 'Outline Color',
    memeDragDrop: 'Drag & Drop an image here',
    // Footer
    footerQuote: 'Full-stack developer crafting modern web experiences.',
    sections: 'Sections',
    pages: 'Pages & tools',
    connect: 'Connect',
    builtWith: 'Built with',
    hostedOn: 'Hosted on',
    rights: 'All rights reserved.',
    allProjects: 'All projects',
    // Students
    students: 'Students',
    studentsTitle: 'Student achievements',
    studentsSubtitle: 'Portfolios built by my students during their training.',
    studentsCount: 'featured portfolios',
    studentsHighlight: 'Built during their training journey',
    // SEO
    seoHomeTitle: "Cherif Diouf | Full-Stack Developer, Digitalization Expert & Trainer – Dakar",
    seoHomeDesc: "Portfolio of El Hadji Ahmadou Cherif Diouf. Laravel, React, Supabase & DevOps Expert. Web/mobile development, business digitalization, prompt engineering and training in Senegal.",
    seoGalleryTitle: "Tech Events & Gallery | Cherif Diouf – Dakar, Senegal",
    seoGalleryDesc: "Photos from conferences, hackathons, graduations and tech events in Senegal. Cherif Diouf, full-stack developer and trainer based in Dakar.",
    seoToolsTitle: "Free Developer Tools | Cherif Diouf",
    seoToolsDesc: "Free open-source tools: GitHub README Generator, WebP Image Converter, Meme Creator. By Cherif Diouf, full-stack developer in Senegal.",
    seoStudentsTitle: "My Students' Achievements | Cherif Diouf – Web Trainer",
    seoStudentsDesc: "Web portfolios built by Cherif Diouf's students during their web development training in Dakar (ESTM, ISM, ESCOA).",
    // Profile switcher
    profileSoftware: 'Software Engineering',
    profileNetwork: 'Network Admin',
    profileTeaching: 'Teaching',
    viewProjects: 'Explore my work',
    contactCta: "Let's talk",
    publications: 'Publications',
  },
  zh: {
    home: '首页',
    gallery: '画廊',
    tools: '工具',
    about: '关于',
    experience: '经历',
    projects: '项目',
    skills: '技能',
    education: '教育',
    available: '可接受新项目',
    role: '开发者',
    and: '&',
    mentor: '导师',
    download: '下载',
    resume: '简历',
    base: '常驻',
    status: '状态',
    top: '顶部',
    selectedProjects: '精选项目',
    technicalSkills: '技术技能',
    workExperience: '工作经历',
    educationTitle: '教育背景',
    galleryTitle: '时刻 & 活动',
    gallerySubtitle: '会议、黑客马拉松和社区生活。',
    toolsTitle: '开发工具箱',
    toolsSubtitle: '为开发者和创作者提供的实用工具。',
    toolReadme: 'Readme 生成器',
    toolReadmeDesc: '使用动态徽章和统计数据创建完美的 GitHub 个人资料。',
    toolMeme: 'Meme 生成器',
    toolMemeDesc: '为您的社交媒体快速创建病毒式内容。',
    toolConverter: '图像转换器',
    toolConverterDesc: '优化资源：一次转换 1 张图像或批量处理 10 张。',
    launch: '启动',
    searchPlaceholder: '搜索项目...',
    startProject: '提交项目需求',
    submitProjectTitle: '讨论您的项目',
    submitProjectDesc: '请填写下面的表格，我会尽快回复您。',
    firstName: '名字',
    lastName: '姓氏',
    email: '电子邮件',
    projectDetails: '项目详情',
    attachFile: '附件',
    filePlaceholder: '拖动文件或点击上传',
    send: '发送请求',
    cancel: '取消',
    successMessage: '您的请求已成功发送！',
    memeTopText: '顶部文字',
    memeBottomText: '底部文字',
    memeUpload: '上传图片',
    memeDownload: '下载 Meme',
    memeFontSize: '字体大小',
    memeTextColor: '文字颜色',
    memeStrokeColor: '描边颜色',
    memeDragDrop: '将图片拖放到此处',
    // Footer
    footerQuote: '打造现代网络体验的全栈开发人员。',
    sections: '章节',
    pages: '页面与工具',
    connect: '连接',
    builtWith: '构建于',
    hostedOn: '托管于',
    rights: '版权所有。',
    allProjects: '所有项目',
    // Students
    students: '学生',
    studentsTitle: '学生作品',
    studentsSubtitle: '我的学生在培训期间制作的作品集。',
    studentsCount: '个精选作品集',
    studentsHighlight: '在培训过程中创建',
    // SEO
    seoHomeTitle: "Cherif Diouf | 全栈开发者、数字化专家 & 讲师 – 达喀尔",
    seoHomeDesc: "El Hadji Ahmadou Cherif Diouf 的作品集。Laravel、React、Supabase & DevOps 专家。塞内加尔网页/移动应用开发、企业数字化转型与提示工程。",
    seoGalleryTitle: "技术活动图库 | Cherif Diouf – 达喀尔，塞内加尔",
    seoGalleryDesc: "塞内加尔技术会议、黑客马拉松和毕业典礼的精彩瞬间。全栈开发者 Cherif Diouf。",
    seoToolsTitle: "免费开发者工具 | Cherif Diouf",
    seoToolsDesc: "免费开源工具：GitHub README 生成器、WebP 图片转换器、Meme 创建器。由塞内加尔全栈开发者 Cherif Diouf 提供。",
    seoStudentsTitle: "学生作品展示 | Cherif Diouf 讲师",
    seoStudentsDesc: "Cherif Diouf 在达喀尔（ESTM、ISM、ESCOA）教授Web开发期间学生制作的作品集。",
    // Profile switcher
    profileSoftware: '软件工程',
    profileNetwork: '网络管理',
    profileTeaching: '教学',
    viewProjects: '探索我的项目',
    contactCta: '一起合作',
    publications: '发表论文',
  },
  ja: {
    home: 'ホーム',
    gallery: 'ギャラリー',
    tools: 'ツール',
    about: '私について',
    experience: '経歴',
    projects: 'プロジェクト',
    skills: 'スキル',
    education: '学歴',
    available: '新規案件募集中',
    role: '開発者',
    and: '&',
    mentor: '講師',
    download: 'ダウンロード',
    resume: '履歴書',
    base: '拠点',
    status: 'ステータス',
    top: 'トップ',
    selectedProjects: '主なプロジェクト',
    technicalSkills: '技術スキル',
    workExperience: '職務経歴',
    educationTitle: '学歴',
    galleryTitle: '瞬間 & イベント',
    gallerySubtitle: 'カンファレンス、ハッカソン、コミュニティライフ。',
    toolsTitle: '開発ツールボックス',
    toolsSubtitle: '開発者とクリエイターのための便利なユーティリティ。',
    toolReadme: 'Readme ジェネレーター',
    toolReadmeDesc: '動的なバッジと統計を使用して完璧な GitHub プロファイルを作成します。',
    toolMeme: 'ミームジェネレーター',
    toolMemeDesc: 'ソーシャルメディア向けのバイラルコンテンツをすばやく作成します。',
    toolConverter: '画像コンバーター',
    toolConverterDesc: 'アセットの最適化：1枚の画像または10枚のバッチを同時に変換します。',
    launch: '起動',
    searchPlaceholder: 'プロジェクトを検索...',
    startProject: 'プロジェクトを提案',
    submitProjectTitle: 'プロジェクトについて相談する',
    submitProjectDesc: '以下のフォームにご記入ください。すぐにご連絡いたします。',
    firstName: '名',
    lastName: '姓',
    email: 'メールアドレス',
    projectDetails: 'プロジェクトの詳細',
    attachFile: 'ファイルを添付',
    filePlaceholder: 'ファイルをドラッグまたはクリック',
    send: '送信する',
    cancel: 'キャンセル',
    successMessage: 'リクエストは正常に送信されました！',
    memeTopText: '上部のテキスト',
    memeBottomText: '下部のテキスト',
    memeUpload: '画像をアップロード',
    memeDownload: 'ミームをダウンロード',
    memeFontSize: 'フォントサイズ',
    memeTextColor: 'テキストの色',
    memeStrokeColor: 'アウトラインの色',
    memeDragDrop: 'ここに画像をドラッグ＆ドロップ',
    // Footer
    footerQuote: 'モダンなWeb体験を作り出すフルスタック開発者。',
    sections: 'セクション',
    pages: 'ページとツール',
    connect: 'SNS',
    builtWith: '使用技術',
    hostedOn: 'ホスティング',
    rights: '無断複写・転載を禁じます。',
    allProjects: 'すべてのプロジェクト',
    // Students
    students: '学生',
    studentsTitle: '学生の実績',
    studentsSubtitle: 'トレーニング中に学生が制作したポートフォリオ。',
    studentsCount: '件の注目ポートフォリオ',
    studentsHighlight: 'トレーニング中に制作',
    // SEO
    seoHomeTitle: "Cherif Diouf | フルスタック開発者、デジタル化専門家 & 講師 – ダカール",
    seoHomeDesc: "El Hadji Ahmadou Cherif Diouf のポートフォリオ。Laravel、React、Supabase & DevOps のエキスパート。セネガルでのWeb/モバイル開発、企業デジタル化とプロンプトエンジニアリング。",
    seoGalleryTitle: "技術イベント & ギャラリー | Cherif Diouf – ダカール",
    seoGalleryDesc: "セネガルのカンファレンス、ハッカソン、卒業式のハイライト。フルスタック開発者 Cherif Diouf。",
    seoToolsTitle: "無料開発者ツール | Cherif Diouf",
    seoToolsDesc: "無料オープンソースツール：GitHub READMEジェネレーター、WebP画像コンバーター、ミームクリエーター。セネガルのフルスタック開発者 Cherif Diouf 提供。",
    seoStudentsTitle: "学生の実績展示 | Cherif Diouf 講師",
    seoStudentsDesc: "ダカール（ESTM、ISM、ESCOA）でのWeb開発研修中に Cherif Diouf の学生が制作したポートフォリオ。",
    // Profile switcher
    profileSoftware: 'ソフトウェア工学',
    profileNetwork: 'ネットワーク管理',
    profileTeaching: '教育',
    viewProjects: '作品を見る →',
    contactCta: '話しましょう',
    publications: '論文',
  }
};
