import type { Language } from '@/types';

export const UI_LABELS: Record<Language, Record<string, string>> = {
  fr: {
    home: 'Accueil',
    gallery: 'Galerie',
    tools: 'Outils',
    about: 'À Propos',
    experience: 'Expériences',
    projects: 'Projets',
    skills: 'Compétences',
    education: 'Formation',
    available: 'Disponible pour nouveaux projets',
    role: 'Développeur',
    and: '&',
    mentor: 'Formateur',
    download: 'Télécharger',
    resume: 'CV',
    base: 'Base',
    status: 'Statut',
    top: 'Haut',
    selectedProjects: 'Projets sélectionnés',
    technicalSkills: 'Compétences techniques',
    workExperience: 'Expériences professionnelles',
    educationTitle: 'Formation académique',
    galleryTitle: 'Moments & événements',
    gallerySubtitle: 'Conférences, hackathons et vie communautaire.',
    toolsTitle: 'Boîte à outils',
    toolsSubtitle: 'Des utilitaires pratiques pour développeurs et créateurs.',
    toolReadme: 'Générateur readme',
    toolReadmeDesc: 'Créez le profil GitHub parfait avec des badges et stats dynamiques.',
    toolMeme: 'Générateur de meme',
    toolMemeDesc: 'Créez du contenu viral rapidement pour vos réseaux sociaux.',
    toolConverter: 'Convertisseur d\'images',
    toolConverterDesc: 'Optimisez vos assets : convertissez 1 image ou un lot de 10 simultanément.',
    launch: 'Lancer',
    searchPlaceholder: 'Rechercher un projet...',
    startProject: 'Démarrer un projet',
    submitProjectTitle: 'Parlons de votre projet',
    submitProjectDesc: 'Remplissez le formulaire ci-dessous et je vous répondrai rapidement.',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    projectDetails: 'Détails du projet',
    attachFile: 'Joindre un fichier',
    filePlaceholder: 'Glissez un fichier ou cliquez',
    send: 'Envoyer la demande',
    cancel: 'Annuler',
    successMessage: 'Votre demande a été envoyée avec succès !',
    memeTopText: 'Texte du Haut',
    memeBottomText: 'Texte du Bas',
    memeUpload: 'Importer une image',
    memeDownload: 'Télécharger le Meme',
    memeFontSize: 'Taille du texte',
    memeTextColor: 'Couleur du texte',
    memeStrokeColor: 'Couleur du contour',
    memeDragDrop: 'Glissez une image ici',
    // Footer
    footerQuote: 'Développeur Full-stack créant des expériences web modernes.',
    sections: 'Sections',
    pages: 'Pages & outils',
    connect: 'Me suivre',
    builtWith: 'Construit avec',
    hostedOn: 'Hébergé sur',
    rights: 'Tous droits réservés.',
    allProjects: 'Tous les projets',
    // SEO
    seoHomeTitle: "Cherif Diouf | Ingénieur Full-Stack & Formateur",
    seoHomeDesc: "Portfolio de Cherif Diouf. Expert Laravel, React & DevOps. Découvrez mes projets, compétences et parcours.",
    seoGalleryTitle: "Galerie & Événements | Cherif Diouf",
    seoGalleryDesc: "Retour en images sur les conférences, hackathons et événements tech au Sénégal.",
    seoToolsTitle: "Boîte à Outils Développeur | Cherif Diouf",
    seoToolsDesc: "Collection d'outils gratuits pour développeurs : Readme Generator, Convertisseur d'Images, Créateur de Memes."
  },
  en: {
    home: 'Home',
    gallery: 'Gallery',
    tools: 'Tools',
    about: 'About',
    experience: 'Experience',
    projects: 'Projects',
    skills: 'Skills',
    education: 'Education',
    available: 'Available for new projects',
    role: 'Developer',
    and: '&',
    mentor: 'Mentor',
    download: 'Download',
    resume: 'Resume',
    base: 'Base',
    status: 'Status',
    top: 'Top',
    selectedProjects: 'Selected projects',
    technicalSkills: 'Technical skills',
    workExperience: 'Work experience',
    educationTitle: 'Education',
    galleryTitle: 'Moments & events',
    gallerySubtitle: 'Conferences, hackathons and community life.',
    toolsTitle: 'Dev toolbox',
    toolsSubtitle: 'Useful utilities for developers and creators.',
    toolReadme: 'Readme generator',
    toolReadmeDesc: 'Create the perfect GitHub profile with dynamic badges and stats.',
    toolMeme: 'Meme generator',
    toolMemeDesc: 'Create viral content quickly for your social media.',
    toolConverter: 'Image converter',
    toolConverterDesc: 'Optimize assets: convert 1 image or a batch of 10 simultaneously.',
    launch: 'Launch',
    searchPlaceholder: 'Search projects...',
    startProject: 'Start a project',
    submitProjectTitle: "Let's discuss your project",
    submitProjectDesc: 'Fill out the form below and I will get back to you shortly.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    projectDetails: 'Project Details',
    attachFile: 'Attach File',
    filePlaceholder: 'Drag a file or click to upload',
    send: 'Send Request',
    cancel: 'Cancel',
    successMessage: 'Your request has been sent successfully!',
    memeTopText: 'Top Text',
    memeBottomText: 'Bottom Text',
    memeUpload: 'Upload Image',
    memeDownload: 'Download Meme',
    memeFontSize: 'Font Size',
    memeTextColor: 'Text Color',
    memeStrokeColor: 'Outline Color',
    memeDragDrop: 'Drag & Drop an image here',
    // Footer
    footerQuote: 'Full-stack developer crafting modern web experiences.',
    sections: 'Sections',
    pages: 'Pages & tools',
    connect: 'Connect',
    builtWith: 'Built with',
    hostedOn: 'Hosted on',
    rights: 'All rights reserved.',
    allProjects: 'All projects',
    // SEO
    seoHomeTitle: "Cherif Diouf | Full-Stack Engineer & Trainer",
    seoHomeDesc: "Portfolio of Cherif Diouf. Laravel, React & DevOps Expert. Discover my projects, skills, and journey.",
    seoGalleryTitle: "Gallery & Events | Cherif Diouf",
    seoGalleryDesc: "Highlights from conferences, hackathons, and tech community events.",
    seoToolsTitle: "Developer Toolbox | Cherif Diouf",
    seoToolsDesc: "Free tools for developers: Readme Generator, Image Converter, Meme Generator."
  },
  zh: {
    home: '首页',
    gallery: '画廊',
    tools: '工具',
    about: '关于',
    experience: '经历',
    projects: '项目',
    skills: '技能',
    education: '教育',
    available: '可接受新项目',
    role: '开发者',
    and: '&',
    mentor: '导师',
    download: '下载',
    resume: '简历',
    base: '常驻',
    status: '状态',
    top: '顶部',
    selectedProjects: '精选项目',
    technicalSkills: '技术技能',
    workExperience: '工作经历',
    educationTitle: '教育背景',
    galleryTitle: '时刻 & 活动',
    gallerySubtitle: '会议、黑客马拉松和社区生活。',
    toolsTitle: '开发工具箱',
    toolsSubtitle: '为开发者和创作者提供的实用工具。',
    toolReadme: 'Readme 生成器',
    toolReadmeDesc: '使用动态徽章和统计数据创建完美的 GitHub 个人资料。',
    toolMeme: 'Meme 生成器',
    toolMemeDesc: '为您的社交媒体快速创建病毒式内容。',
    toolConverter: '图像转换器',
    toolConverterDesc: '优化资源：一次转换 1 张图像或批量处理 10 张。',
    launch: '启动',
    searchPlaceholder: '搜索项目...',
    startProject: '开始新项目',
    submitProjectTitle: '讨论您的项目',
    submitProjectDesc: '请填写下面的表格，我会尽快回复您。',
    firstName: '名字',
    lastName: '姓氏',
    email: '电子邮件',
    projectDetails: '项目详情',
    attachFile: '附件',
    filePlaceholder: '拖动文件或点击上传',
    send: '发送请求',
    cancel: '取消',
    successMessage: '您的请求已成功发送！',
    memeTopText: '顶部文字',
    memeBottomText: '底部文字',
    memeUpload: '上传图片',
    memeDownload: '下载 Meme',
    memeFontSize: '字体大小',
    memeTextColor: '文字颜色',
    memeStrokeColor: '描边颜色',
    memeDragDrop: '将图片拖放到此处',
    // Footer
    footerQuote: '打造现代网络体验的全栈开发人员。',
    sections: '章节',
    pages: '页面与工具',
    connect: '连接',
    builtWith: '构建于',
    hostedOn: '托管于',
    rights: '版权所有。',
    allProjects: '所有项目',
    // SEO
    seoHomeTitle: "Cherif Diouf | 全栈工程师 & 讲师",
    seoHomeDesc: "Cherif Diouf 的作品集。Laravel, React & DevOps 专家。探索我的项目、技能和经历。",
    seoGalleryTitle: "画廊 & 活动 | Cherif Diouf",
    seoGalleryDesc: "会议、黑客马拉松和技术社区活动集锦。",
    seoToolsTitle: "开发者工具箱 | Cherif Diouf",
    seoToolsDesc: "开发者免费工具：Readme 生成器、图像转换器、Meme 生成器。"
  },
  ja: {
    home: 'ホーム',
    gallery: 'ギャラリー',
    tools: 'ツール',
    about: '私について',
    experience: '経歴',
    projects: 'プロジェクト',
    skills: 'スキル',
    education: '学歴',
    available: '新規案件募集中',
    role: '開発者',
    and: '&',
    mentor: '講師',
    download: 'ダウンロード',
    resume: '履歴書',
    base: '拠点',
    status: 'ステータス',
    top: 'トップ',
    selectedProjects: '主なプロジェクト',
    technicalSkills: '技術スキル',
    workExperience: '職務経歴',
    educationTitle: '学歴',
    galleryTitle: '瞬間 & イベント',
    gallerySubtitle: 'カンファレンス、ハッカソン、コミュニティライフ。',
    toolsTitle: '開発ツールボックス',
    toolsSubtitle: '開発者とクリエイターのための便利なユーティリティ。',
    toolReadme: 'Readme ジェネレーター',
    toolReadmeDesc: '動的なバッジと統計を使用して完璧な GitHub プロファイルを作成します。',
    toolMeme: 'ミームジェネレーター',
    toolMemeDesc: 'ソーシャルメディア向けのバイラルコンテンツをすばやく作成します。',
    toolConverter: '画像コンバーター',
    toolConverterDesc: 'アセットの最適化：1枚の画像または10枚のバッチを同時に変換します。',
    launch: '起動',
    searchPlaceholder: 'プロジェクトを検索...',
    startProject: 'プロジェクトを開始',
    submitProjectTitle: 'プロジェクトについて相談する',
    submitProjectDesc: '以下のフォームにご記入ください。すぐにご連絡いたします。',
    firstName: '名',
    lastName: '姓',
    email: 'メールアドレス',
    projectDetails: 'プロジェクトの詳細',
    attachFile: 'ファイルを添付',
    filePlaceholder: 'ファイルをドラッグまたはクリック',
    send: '送信する',
    cancel: 'キャンセル',
    successMessage: 'リクエストは正常に送信されました！',
    memeTopText: '上部のテキスト',
    memeBottomText: '下部のテキスト',
    memeUpload: '画像をアップロード',
    memeDownload: 'ミームをダウンロード',
    memeFontSize: 'フォントサイズ',
    memeTextColor: 'テキストの色',
    memeStrokeColor: 'アウトラインの色',
    memeDragDrop: 'ここに画像をドラッグ＆ドロップ',
    // Footer
    footerQuote: 'モダンなWeb体験を作り出すフルスタック開発者。',
    sections: 'セクション',
    pages: 'ページとツール',
    connect: 'SNS',
    builtWith: '使用技術',
    hostedOn: 'ホスティング',
    rights: '無断複写・転載を禁じます。',
    allProjects: 'すべてのプロジェクト',
    // SEO
    seoHomeTitle: "Cherif Diouf | フルスタックエンジニア & 講師",
    seoHomeDesc: "Cherif Diouf のポートフォリオ。Laravel, React & DevOps のエキスパート。私のプロジェクト、スキル、経歴をご覧ください。",
    seoGalleryTitle: "ギャラリー & イベント | Cherif Diouf",
    seoGalleryDesc: "カンファレンス、ハッカソン、テックコミュニティイベントのハイライト。",
    seoToolsTitle: "開発者ツールボックス | Cherif Diouf",
    seoToolsDesc: "開発者向け無料ツール：Readme ジェネレーター、画像コンバーター、ミームジェネレーター。"
  }
};
