import type { Locale } from '@/lib/i18n';

const en = {
  local: 'Private by design', localNote: 'Your files stay in this browser. No upload, account or server processing.',
  images: 'Images & PDF', data: 'CSV & JSON', imageTitle: 'A lighter file. The same idea.', imageSubtitle: 'Convert a batch, compare the result, take only what you need.',
  format: 'Output format', quality: 'Image quality', qualityNote: 'Higher quality usually means a larger file.', lossless: 'Lossless output. Quality adjustment does not apply.', pdfNote: 'One image per PDF, with a white background. PDF input is not supported.',
  drop: 'Drop images here', browse: 'Choose images', dropNote: 'PNG, JPEG, WebP, GIF, BMP · up to 20 files · 30 MB each · 100 MB total', firstFrame: 'Still images only: animated GIF/WebP use the first frame. JPEG uses a white background; PNG and WebP keep transparency. Metadata is not preserved.',
  convert: 'Convert files', converting: 'Converting', reset: 'Reset all', ready: 'Ready', pending: 'Awaiting conversion', failed: 'Could not convert', download: 'Download', downloadAll: 'Download ZIP', zipping: 'Preparing ZIP', remove: 'Remove', original: 'Original', result: 'Converted', smaller: 'smaller', larger: 'larger', unchanged: 'same size', files: 'files', complete: 'completed', emptyTitle: 'Your next conversion starts here', emptyText: 'Choose a format, then add your images. Conversion starts automatically. Change settings to convert them again.', preview: 'Converted preview', settings: 'Conversion settings', queue: 'Files & results', fresh: 'Settings changed. Convert again to get updated files.',
  dataTitle: 'Make structured data readable.', dataSubtitle: 'Convert comma-separated CSV to JSON records, or turn flat JSON records into CSV.', operation: 'Operation', csvJson: 'CSV → JSON', jsonCsv: 'JSON → CSV', pretty: 'Format JSON', compact: 'Minify JSON', import: 'Import a file', source: 'Source', output: 'Result', sample: 'Load an example', dataConvert: 'Convert data', copy: 'Copy result', copied: 'Copied', copyFailed: 'Copy failed. Select and copy the result manually.', dataPlaceholder: 'Paste CSV or JSON here…', outputPlaceholder: 'Your converted data appears here.', dataNote: 'UTF-8 · 5 MB maximum. CSV values stay strings. JSON → CSV accepts a non-empty array of flat objects; nested data is rejected. Missing values and null become empty cells.', protect: 'Protect spreadsheet formulas', protectNote: 'Prefix cells starting with =, +, - or @ with an apostrophe. This changes those cell values to prevent formula execution.', dataFresh: 'Source or options changed. Convert again to refresh the result.',
  memeTitle: 'Make the caption land.', memeSubtitle: 'Your image, your words, a PNG ready to share.', image: 'Image', uploadImage: 'Choose an image', uploadNote: 'PNG, JPEG, WebP, GIF or BMP · up to 30 MB. Export is resized to a maximum of 1600 px. Animated images use the first frame.', top: 'Top caption', bottom: 'Bottom caption', defaultTop: 'ONE SMALL IDEA', defaultBottom: 'A WHOLE NEW SYSTEM', typography: 'Typography', font: 'Font family', impact: 'Bold display', sans: 'Sans serif', serif: 'Serif', mono: 'Monospace', fontSize: 'Font size', textColor: 'Text color', strokeColor: 'Outline color', stroke: 'Outline width', uppercase: 'UPPERCASE captions', captionNote: 'Captions wrap automatically, including Chinese and Japanese. Long captions shrink to stay inside the image.', export: 'Export PNG', exporting: 'Exporting', exported: 'PNG download started', resetMeme: 'Reset composition', livePreview: 'Live preview', demo: 'Built-in canvas', loading: 'Loading image', canvasAlt: 'Meme preview with the current image and captions', canvasFallback: 'Your browser needs canvas support to display and export this image.', exportSize: 'Export size', characters: 'characters',
  errors: { unsupported: 'Unsupported file. Choose a genuine PNG, JPEG, WebP, GIF or BMP image.', tooLarge: 'This file is too large. Images: 30 MB maximum. Text: 5 MB maximum.', tooMany: 'You can convert up to 20 images at a time.', batchSize: 'This batch exceeds 100 MB. Remove files or convert a smaller batch.', outputLimit: 'Converted files exceed the 150 MB memory limit. Download and remove some results, then retry.', dataLimit: 'This conversion is too large. Use at most 50,000 rows, 500 columns and a smaller output.', pixels: 'This image is too large to process safely. Use at most 24 megapixels and 10,000 px per side.', decode: 'This image could not be read. It may be damaged or unsupported by this browser.', encode: 'This browser could not create the requested format. Try PNG or another browser.', empty: 'Add a non-empty file or paste some content first.', csv: 'Invalid CSV quoting. Use commas and double quotes; escape quotes as two double quotes.', headers: 'Use unique, non-empty column names in the first CSV row or JSON keys.', rows: 'Every CSV row must have the same number of columns as its header.', json: 'Invalid JSON. Check brackets, double quotes and trailing commas.', records: 'Use a non-empty JSON array of objects, such as [{"name":"Ada"}].', nested: 'Nested objects and arrays are not supported in CSV. Flatten the data first.', utf8: 'This file is not valid UTF-8 text. Save it as UTF-8 and try again.', unknown: 'Something went wrong. Try again with a smaller file.' },
};
type AppCopy = typeof en;
const fr: AppCopy = {
  local: 'Confidentiel par conception', localNote: 'Vos fichiers restent dans ce navigateur. Aucun envoi, compte ou traitement serveur.',
  images: 'Images & PDF', data: 'CSV & JSON', imageTitle: 'Un fichier plus léger. La même idée.', imageSubtitle: 'Convertissez un lot, comparez le résultat, gardez ce qui vous sert.',
  format: 'Format de sortie', quality: 'Qualité de l’image', qualityNote: 'Une qualité élevée produit généralement un fichier plus lourd.', lossless: 'Sortie sans perte. Le réglage de qualité ne s’applique pas.', pdfNote: 'Une image par PDF, sur fond blanc. Les PDF ne sont pas acceptés en entrée.',
  drop: 'Déposez vos images ici', browse: 'Choisir des images', dropNote: 'PNG, JPEG, WebP, GIF, BMP · 20 fichiers maximum · 30 Mo chacun · 100 Mo au total', firstFrame: 'Images fixes uniquement : la première image des GIF/WebP animés est utilisée. Le JPEG a un fond blanc ; PNG et WebP conservent la transparence. Les métadonnées ne sont pas conservées.',
  convert: 'Convertir les fichiers', converting: 'Conversion', reset: 'Tout réinitialiser', ready: 'Prêt', pending: 'En attente de conversion', failed: 'Échec de conversion', download: 'Télécharger', downloadAll: 'Télécharger le ZIP', zipping: 'Préparation du ZIP', remove: 'Retirer', original: 'Original', result: 'Converti', smaller: 'plus léger', larger: 'plus lourd', unchanged: 'même taille', files: 'fichiers', complete: 'terminés', emptyTitle: 'Votre prochaine conversion commence ici', emptyText: 'Choisissez un format puis ajoutez vos images. La conversion démarre automatiquement. Modifiez les réglages pour les convertir à nouveau.', preview: 'Aperçu du résultat', settings: 'Réglages de conversion', queue: 'Fichiers & résultats', fresh: 'Réglages modifiés. Relancez la conversion pour mettre les fichiers à jour.',
  dataTitle: 'Des données structurées, lisibles.', dataSubtitle: 'Transformez un CSV séparé par des virgules en objets JSON, ou des objets JSON simples en CSV.', operation: 'Opération', csvJson: 'CSV → JSON', jsonCsv: 'JSON → CSV', pretty: 'Formater le JSON', compact: 'Compacter le JSON', import: 'Importer un fichier', source: 'Source', output: 'Résultat', sample: 'Charger un exemple', dataConvert: 'Convertir les données', copy: 'Copier le résultat', copied: 'Copié', copyFailed: 'Copie impossible. Sélectionnez et copiez le résultat manuellement.', dataPlaceholder: 'Collez votre CSV ou JSON ici…', outputPlaceholder: 'Les données converties apparaîtront ici.', dataNote: 'UTF-8 · 5 Mo maximum. Les valeurs CSV restent des chaînes. JSON → CSV accepte un tableau non vide d’objets simples, sans données imbriquées. Les valeurs absentes et null deviennent des cellules vides.', protect: 'Neutraliser les formules de tableur', protectNote: 'Ajoute une apostrophe aux cellules commençant par =, +, - ou @. Leur valeur est modifiée pour empêcher l’exécution de formules.', dataFresh: 'Source ou options modifiées. Relancez la conversion pour actualiser le résultat.',
  memeTitle: 'Trouvez la bonne formule.', memeSubtitle: 'Votre image, vos mots, un PNG prêt à partager.', image: 'Image', uploadImage: 'Choisir une image', uploadNote: 'PNG, JPEG, WebP, GIF ou BMP · 30 Mo maximum. Export redimensionné à 1 600 px maximum. Première image pour les animations.', top: 'Texte du haut', bottom: 'Texte du bas', defaultTop: 'UNE PETITE IDÉE', defaultBottom: 'TOUT UN NOUVEAU SYSTÈME', typography: 'Typographie', font: 'Famille de police', impact: 'Affiche en gras', sans: 'Sans empattement', serif: 'Avec empattement', mono: 'Chasse fixe', fontSize: 'Taille du texte', textColor: 'Couleur du texte', strokeColor: 'Couleur du contour', stroke: 'Épaisseur du contour', uppercase: 'Textes en MAJUSCULES', captionNote: 'Les textes passent à la ligne, y compris en chinois et japonais. Les textes longs sont réduits pour rester dans l’image.', export: 'Exporter en PNG', exporting: 'Export en cours', exported: 'Téléchargement du PNG lancé', resetMeme: 'Réinitialiser la composition', livePreview: 'Aperçu en direct', demo: 'Fond intégré', loading: 'Chargement de l’image', canvasAlt: 'Aperçu du mème avec l’image et les textes actuels', canvasFallback: 'Votre navigateur doit prendre en charge le canvas pour afficher et exporter cette image.', exportSize: 'Dimensions d’export', characters: 'caractères',
  errors: { unsupported: 'Format non pris en charge. Choisissez une véritable image PNG, JPEG, WebP, GIF ou BMP.', tooLarge: 'Ce fichier est trop lourd. Images : 30 Mo maximum. Texte : 5 Mo maximum.', tooMany: 'Vous pouvez convertir 20 images à la fois au maximum.', batchSize: 'Ce lot dépasse 100 Mo. Retirez des fichiers ou convertissez un lot plus petit.', outputLimit: 'Les résultats dépassent la limite de mémoire de 150 Mo. Téléchargez et retirez des résultats, puis réessayez.', dataLimit: 'Cette conversion est trop grande. Limitez les données à 50 000 lignes, 500 colonnes et une sortie plus petite.', pixels: 'Cette image est trop grande. Limites : 24 mégapixels et 10 000 px par côté.', decode: 'Impossible de lire cette image. Elle est peut-être endommagée ou non prise en charge par ce navigateur.', encode: 'Ce navigateur ne peut pas créer ce format. Essayez le PNG ou un autre navigateur.', empty: 'Ajoutez un fichier non vide ou collez du contenu.', csv: 'Guillemets CSV invalides. Utilisez des virgules et doublez les guillemets présents dans une valeur.', headers: 'Les noms de colonnes CSV et les clés JSON doivent être uniques et non vides.', rows: 'Chaque ligne CSV doit avoir autant de colonnes que l’en-tête.', json: 'JSON invalide. Vérifiez les crochets, les guillemets doubles et les virgules finales.', records: 'Utilisez un tableau JSON non vide d’objets, comme [{"nom":"Ada"}].', nested: 'Les objets et tableaux imbriqués ne sont pas acceptés en CSV. Aplatissez les données.', utf8: 'Ce fichier n’est pas un texte UTF-8 valide. Enregistrez-le en UTF-8 puis réessayez.', unknown: 'Une erreur est survenue. Réessayez avec un fichier plus petit.' },
};
const zh: AppCopy = {
  local: '隐私优先', localNote: '文件始终保留在当前浏览器中。无需上传、账号或服务器处理。',
  images: '图片与 PDF', data: 'CSV 与 JSON', imageTitle: '更轻的文件，同样的想法。', imageSubtitle: '批量转换，比较结果，只下载所需文件。',
  format: '输出格式', quality: '图片质量', qualityNote: '质量越高，文件通常越大。', lossless: '无损输出，无需调整质量。', pdfNote: '每张图片生成一个白底 PDF。不支持导入 PDF。',
  drop: '将图片拖到这里', browse: '选择图片', dropNote: 'PNG、JPEG、WebP、GIF、BMP · 最多 20 个文件 · 每个不超过 30 MB · 总计 100 MB', firstFrame: '仅输出静态图片：GIF/WebP 动画取首帧。JPEG 使用白色背景；PNG 和 WebP 保留透明度。不保留元数据。',
  convert: '转换文件', converting: '正在转换', reset: '全部重置', ready: '已就绪', pending: '等待转换', failed: '转换失败', download: '下载', downloadAll: '下载 ZIP', zipping: '正在生成 ZIP', remove: '移除', original: '原始文件', result: '转换结果', smaller: '缩小', larger: '增大', unchanged: '大小不变', files: '个文件', complete: '已完成', emptyTitle: '从这里开始转换', emptyText: '选择格式并添加图片，即可自动开始转换。修改设置后可重新转换。', preview: '转换结果预览', settings: '转换设置', queue: '文件与结果', fresh: '设置已更改。请重新转换以更新文件。',
  dataTitle: '让结构化数据清晰可读。', dataSubtitle: '将逗号分隔的 CSV 转成 JSON 记录，或将扁平 JSON 记录转成 CSV。', operation: '操作', csvJson: 'CSV → JSON', jsonCsv: 'JSON → CSV', pretty: '格式化 JSON', compact: '压缩 JSON', import: '导入文件', source: '源数据', output: '结果', sample: '载入示例', dataConvert: '转换数据', copy: '复制结果', copied: '已复制', copyFailed: '复制失败，请手动选择并复制结果。', dataPlaceholder: '在此粘贴 CSV 或 JSON…', outputPlaceholder: '转换结果将显示在这里。', dataNote: 'UTF-8 · 最大 5 MB。CSV 值保留为字符串。JSON → CSV 需要包含扁平对象的非空数组，不接受嵌套数据。缺失值和 null 转为空单元格。', protect: '防止电子表格公式执行', protectNote: '为以 =、+、- 或 @ 开头的单元格添加单引号。此操作会修改这些值，防止作为公式执行。', dataFresh: '源数据或选项已更改，请重新转换。',
  memeTitle: '让文字点亮图片。', memeSubtitle: '你的图片，你的文字，随时分享的 PNG。', image: '图片', uploadImage: '选择图片', uploadNote: 'PNG、JPEG、WebP、GIF 或 BMP · 最大 30 MB。导出最长边不超过 1600 像素。动画仅取首帧。', top: '顶部文字', bottom: '底部文字', defaultTop: '一个小小的想法', defaultBottom: '一套全新的系统', typography: '字体设置', font: '字体', impact: '粗体标题', sans: '无衬线字体', serif: '衬线字体', mono: '等宽字体', fontSize: '字号', textColor: '文字颜色', strokeColor: '描边颜色', stroke: '描边宽度', uppercase: '英文文字转为大写', captionNote: '文字自动换行，支持中文和日文。较长文字将缩小以适应图片。', export: '导出 PNG', exporting: '正在导出', exported: 'PNG 已开始下载', resetMeme: '重置创作', livePreview: '实时预览', demo: '内置画布', loading: '正在加载图片', canvasAlt: '当前图片与文字的表情包预览', canvasFallback: '浏览器需要支持 canvas 才能显示和导出图片。', exportSize: '导出尺寸', characters: '个字符',
  errors: { unsupported: '不支持此文件，请选择有效的 PNG、JPEG、WebP、GIF 或 BMP 图片。', tooLarge: '文件过大。图片最大 30 MB，文本最大 5 MB。', tooMany: '每次最多转换 20 张图片。', batchSize: '此批次超过 100 MB。请移除部分文件或减少批量大小。', outputLimit: '转换结果超过 150 MB 内存限制。请下载并移除部分结果，然后重试。', dataLimit: '转换数据过大。请限制在 50000 行、500 列以内，并减少输出大小。', pixels: '图片尺寸过大。最多 2400 万像素，单边不超过 10000 像素。', decode: '无法读取图片，文件可能损坏或浏览器不支持此格式。', encode: '浏览器无法生成此格式，请尝试 PNG 或其他浏览器。', empty: '请添加非空文件或粘贴内容。', csv: 'CSV 引号格式不正确。使用逗号分隔，并用两个双引号表示值中的双引号。', headers: 'CSV 列名和 JSON 键必须唯一且非空。', rows: '每行 CSV 的列数必须与表头一致。', json: 'JSON 无效，请检查括号、双引号和末尾逗号。', records: '请使用非空 JSON 对象数组，例如 [{"姓名":"Ada"}]。', nested: 'CSV 不支持嵌套对象和数组，请先展平数据。', utf8: '此文件不是有效的 UTF-8 文本，请保存为 UTF-8 后重试。', unknown: '发生错误，请尝试更小的文件。' },
};
const ja: AppCopy = {
  local: 'プライバシーを大切に', localNote: 'ファイルはこのブラウザ内で処理されます。アップロード、アカウント、サーバー処理は不要です。',
  images: '画像・PDF', data: 'CSV・JSON', imageTitle: 'ファイルは軽く、アイデアはそのまま。', imageSubtitle: 'まとめて変換し、結果を比べて、必要なものをダウンロード。',
  format: '出力形式', quality: '画質', qualityNote: '画質を上げると、通常はファイルも大きくなります。', lossless: '可逆圧縮です。画質の調整は適用されません。', pdfNote: '1画像につき白背景のPDFを作成。PDFの入力には対応していません。',
  drop: 'ここに画像をドロップ', browse: '画像を選択', dropNote: 'PNG・JPEG・WebP・GIF・BMP · 最大20ファイル · 各30 MB・合計100 MBまで', firstFrame: '静止画のみ。アニメーションGIF/WebPは最初のフレームを使用します。JPEGは白背景、PNGとWebPは透明度を保持します。メタデータは保持されません。',
  convert: 'ファイルを変換', converting: '変換中', reset: 'すべてリセット', ready: '完了', pending: '変換待ち', failed: '変換できませんでした', download: 'ダウンロード', downloadAll: 'ZIPをダウンロード', zipping: 'ZIPを準備中', remove: '削除', original: '元のファイル', result: '変換後', smaller: '縮小', larger: '増加', unchanged: '同じサイズ', files: 'ファイル', complete: '完了', emptyTitle: '次の変換をここから', emptyText: '形式を選んで画像を追加すると、自動的に変換を開始します。設定を変えて再変換することもできます。', preview: '変換結果のプレビュー', settings: '変換設定', queue: 'ファイルと結果', fresh: '設定が変更されました。もう一度変換してファイルを更新してください。',
  dataTitle: '構造化データを読みやすく。', dataSubtitle: 'カンマ区切りCSVをJSONレコードに、フラットなJSONレコードをCSVに変換。', operation: '操作', csvJson: 'CSV → JSON', jsonCsv: 'JSON → CSV', pretty: 'JSONを整形', compact: 'JSONを圧縮', import: 'ファイルを読み込む', source: '入力', output: '結果', sample: 'サンプルを読み込む', dataConvert: 'データを変換', copy: '結果をコピー', copied: 'コピーしました', copyFailed: 'コピーできませんでした。結果を選択して手動でコピーしてください。', dataPlaceholder: 'CSVまたはJSONをここに貼り付け…', outputPlaceholder: '変換結果がここに表示されます。', dataNote: 'UTF-8 · 最大5 MB。CSVの値は文字列のままです。JSON → CSVはフラットなオブジェクトの空でない配列に対応し、入れ子は不可です。欠損値とnullは空のセルになります。', protect: '表計算の数式を無効化', protectNote: '=、+、-、@で始まるセルにアポストロフィを付けます。数式の実行を防ぐため、該当する値が変更されます。', dataFresh: '入力または設定が変更されました。再変換してください。',
  memeTitle: '言葉が伝わる一枚に。', memeSubtitle: '好きな画像とテキストで、共有できるPNGを。', image: '画像', uploadImage: '画像を選択', uploadNote: 'PNG・JPEG・WebP・GIF・BMP · 最大30 MB。書き出しは最長辺1600 pxまで。アニメーションは最初のフレームを使用します。', top: '上のテキスト', bottom: '下のテキスト', defaultTop: '小さなアイデアが', defaultBottom: '新しいシステムになる', typography: 'タイポグラフィ', font: 'フォント', impact: '太字ディスプレイ', sans: 'ゴシック体', serif: '明朝体', mono: '等幅', fontSize: '文字サイズ', textColor: '文字色', strokeColor: '縁取りの色', stroke: '縁取りの太さ', uppercase: '英字を大文字にする', captionNote: '中国語・日本語も自動で折り返します。長い文章は画像に収まるよう縮小されます。', export: 'PNGを書き出す', exporting: '書き出し中', exported: 'PNGのダウンロードを開始しました', resetMeme: '作品をリセット', livePreview: 'ライブプレビュー', demo: '内蔵キャンバス', loading: '画像を読み込み中', canvasAlt: '現在の画像とテキストによるミームのプレビュー', canvasFallback: '表示と書き出しにはcanvas対応ブラウザが必要です。', exportSize: '書き出しサイズ', characters: '文字',
  errors: { unsupported: '対応していないファイルです。有効なPNG、JPEG、WebP、GIF、BMP画像を選んでください。', tooLarge: 'ファイルが大きすぎます。画像は30 MB、テキストは5 MBまでです。', tooMany: '一度に変換できる画像は20枚までです。', batchSize: '合計100 MBを超えています。ファイルを減らして再試行してください。', outputLimit: '変換結果が150 MBのメモリ制限を超えています。一部をダウンロードして削除し、再試行してください。', dataLimit: '変換結果が大きすぎます。50000行、500列以内にし、出力を小さくしてください。', pixels: '画像が大きすぎます。2400万画素、各辺10000 pxまでにしてください。', decode: '画像を読み込めません。破損しているか、このブラウザでは非対応の可能性があります。', encode: 'このブラウザでは指定形式を作成できません。PNGか別のブラウザをお試しください。', empty: '空でないファイルを追加するか、内容を貼り付けてください。', csv: 'CSVの引用符が不正です。カンマ区切りを使用し、値内の引用符は二重にしてください。', headers: 'CSV列名とJSONキーは空でなく、一意にしてください。', rows: '各CSV行の列数をヘッダーと揃えてください。', json: 'JSONが不正です。括弧、二重引用符、末尾のカンマを確認してください。', records: '空でないJSONオブジェクト配列を使用してください。例：[{"名前":"Ada"}]。', nested: 'CSVは入れ子のオブジェクトや配列に対応していません。先にフラット化してください。', utf8: '有効なUTF-8テキストではありません。UTF-8で保存して再試行してください。', unknown: 'エラーが発生しました。小さなファイルで再試行してください。' },
};
export const appCopy: Record<Locale, AppCopy> = { en, fr, zh, ja };
