export const locales = ['fr', 'en', 'zh', 'ja'] as const;
export type Locale = (typeof locales)[number];

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function localePath(locale: Locale, path = '') {
  const suffix = path === '/' ? '' : path;
  return `/${locale}${suffix}`;
}

export function languageAlternates(path = '') {
  return Object.fromEntries(locales.map((locale) => [locale, localePath(locale, path)]));
}

const dictionaries = {
  fr: {
    seo: {
      home: ['Cherif Diouf — Ingénieur Full-Stack & Formateur', 'Portfolio de Cherif Diouf : systèmes utiles, automatisation, IA et transmission.'],
      projects: ['Projets — Cherif Diouf', 'Logiciels publics, systèmes privés documentés et démonstrations vérifiées.'],
      gallery: ['Galerie — Cherif Diouf', 'Conférences, ateliers et traces de transmission.'],
      tools: ['Laboratoire — Cherif Diouf', 'Outils locaux pour convertir, composer et documenter.'],
      image: ['Convertisseur WebP — Cherif Diouf', 'Convertir une image localement en WebP.'],
      meme: ['Générateur de mèmes — Cherif Diouf', 'Composer un visuel local avec deux lignes de texte.'],
      readme: ['Générateur de README — Cherif Diouf', 'Créer un point de départ clair pour la documentation.'],
      students: ['Réalisations de mes étudiants — Cherif Diouf', 'Cinq portfolios web réalisés par les étudiants de Cherif Diouf durant leur formation.'],
    },
    nav: { home: 'Accueil', projects: 'Projets', gallery: 'Galerie', tools: 'Outils', students: 'Étudiants', contact: 'Contact' },
    footer: { eyebrow: 'Contact / collaboration', title: 'Un problème concret à rendre plus simple ?', languages: 'Français · anglais · wolof' },
    home: {
      eyebrow: 'Portfolio / Dakar / 2026', title: ['Des systèmes', 'qui servent', 'vraiment.'], bio: 'Je conçois des systèmes qui font gagner du temps, réduisent les coûts opérationnels et transforment l’expertise en compétences durables.', primary: 'Explorer les preuves', secondary: 'Ouvrir le laboratoire', availability: 'Disponible pour de nouveaux projets', languages: 'Français · anglais · wolof', proofKicker: '02 / ce que je construis', proofTitle: 'La technique devient utile quand elle laisse une preuve.', proofText: 'Un logiciel, une automatisation ou une formation n’a de valeur que s’il réduit une friction réelle. Chaque projet ici est relié à un terrain, une contrainte et un résultat.', proofLink: 'Voir le terrain', experienceKicker: 'Trajectoire / terrain', experienceTitle: 'Une méthode forgée dans plusieurs systèmes.', experienceText: 'Pilotage, sécurité, développement et transmission se répondent dans un même parcours.', labKicker: '04 / couche d’intelligence', labTitle: 'Je n’utilise pas l’IA comme un bouton. Je l’orchestre.', labText: 'Contexte, outils, mémoire, agents et validation humaine : le laboratoire transforme une intention floue en système transmissible.', labCta: 'Entrer dans le laboratoire', skillsKicker: 'Boîte à outils / compétences', skillsTitle: 'Un socle technique, une logique de transmission.', skillsText: 'Les outils changent. La capacité à les relier à un besoin reste.', projectsKicker: '06 / sélection', projectsTitle: 'Projets et preuves publiques.', projectsLink: 'Voir tous les projets', metrics: ['gain observé sur les états financiers', 'compétences IA conçues et maintenues', 'terrains : produit, infra, IA, pédagogie'], identity: 'Full-Stack & transmission', labScene: 'Architecture de travail : contexte, outils et validation humaine', labFaces: ['Contexte', 'Mémoire', 'Outils', 'Agents', 'Validation', 'Résultat'], labNodes: ['contexte', 'action', 'continuité']
    },
    gallery: { kicker: 'Galerie / terrain', title: 'Les lieux où la méthode se construit.', text: 'Conférences, ateliers, communauté et transmission : une galerie issue du corpus public historique.', filter: 'Filtrer la galerie', all: 'Tout', categories: { Transmission: 'Transmission', Communauté: 'Communauté', 'Logiciel libre': 'Logiciel libre', Projet: 'Projet' } },
    tools: { kicker: 'Laboratoire / outils', title: 'Des petits outils pour enlever les petites frictions.', text: 'Trois surfaces locales, utiles immédiatement et lisibles jusque dans leur fonctionnement.', open: 'Ouvrir l’outil', local: 'outil local', cards: { image: ['Convertisseur WebP', 'Convertir une image en WebP côté navigateur.'], meme: ['Générateur de mèmes', 'Composer un visuel simple à partir d’un média local.'], readme: ['Générateur de README', 'Structurer rapidement la documentation d’un projet.'] } },
    image: { kicker: 'Outil / performance', title: 'Convertir une image sans quitter le navigateur.', text: 'Une conversion locale en WebP, sans upload et sans serveur intermédiaire.', caption: 'Image Converter · aperçu du projet', drop: 'Déposer une image ou parcourir', convert: 'Convertir en WebP', download: 'Télécharger converted.webp' },
    meme: { kicker: 'Outil / composition', title: 'Une idée, deux lignes, un visuel.', text: 'Une petite surface de composition pour prototyper un message et le rendre partageable.', top: 'Texte haut', bottom: 'Texte bas', note: 'Démo locale : le texte est rendu dans le navigateur, aucun fichier n’est envoyé.' },
    readme: { kicker: 'Outil / transmission', title: 'Donner un point de départ à la documentation.', text: 'Un README minimal, lisible et modifiable en quelques champs.', name: 'Nom du projet', description: 'Description', copy: 'Copier le README', placeholder: 'Une question sur le portfolio…' },
    students: { kicker: 'Transmission / pédagogie', title: 'Apprendre en construisant quelque chose qui fonctionne.', text: 'Des cours ancrés dans des projets réels, du premier fichier HTML jusqu’au système complet.', eyebrow: 'Un parcours de travail', heading: 'Le code devient une compétence quand on sait expliquer ses choix.', body: 'Formateur PHP, MySQL, HTML, CSS et JavaScript, Cherif accompagne les apprenants avec une progression concrète : comprendre, construire, tester, transmettre.', cta: 'Proposer un atelier', resources: 'Ressources et traces', resourcesText: 'Les projets publics servent de supports de lecture : on part d’un besoin, on suit les décisions, on regarde ce qui tient.', resourcesLink: 'Voir la galerie des ateliers', tracks: [['Frontend', 'HTML, CSS, JavaScript, DOM et responsive design.'], ['Backend', 'PHP, MySQL, Laravel, APIs et architecture MVC.'], ['Méthode', 'Git, UML, revue de code, Kanban et documentation.'], ['IA appliquée', 'Contexte, prompts, RAG, agents et automatisation responsable.']] },
    chat: { assistant: 'Assistant local', title: 'Interroger Cherif', available: 'Disponible', local: 'Réponses locales', initial: 'Bonjour. Je peux vous guider dans le parcours et les projets de Cherif Diouf.', suggestions: ['Parcours', 'Projets publics', 'Compétences', 'Contact'], placeholder: 'Une question sur le portfolio…', send: 'Envoyer la question', close: 'Fermer le chat', source: 'Sources publiques utilisées pour cette réponse', sourceProfile: 'Profil public', sourceProjects: 'Projets publics', sourceSkills: 'Compétences déclarées', sourceExperience: 'Parcours professionnel', sourceTools: 'Outils locaux' },
  },
  en: {
    seo: { home: ['Cherif Diouf — Full-Stack Engineer & Educator', 'Cherif Diouf’s portfolio: useful systems, automation, AI and knowledge sharing.'], projects: ['Projects — Cherif Diouf', 'Public software, documented private systems and verified demonstrations.'], gallery: ['Gallery — Cherif Diouf', 'Conferences, workshops and traces of knowledge sharing.'], tools: ['Lab — Cherif Diouf', 'Local tools to convert, compose and document.'], image: ['WebP Converter — Cherif Diouf', 'Convert an image locally to WebP.'], meme: ['Meme Generator — Cherif Diouf', 'Compose a local visual with two lines of text.'], readme: ['README Generator — Cherif Diouf', 'Create a clear starting point for documentation.'], students: ['Student achievements — Cherif Diouf', 'Five web portfolios built by Cherif Diouf’s students during their training.'] },
    nav: { home: 'Home', projects: 'Projects', gallery: 'Gallery', tools: 'Tools', students: 'Students', contact: 'Contact' }, footer: { eyebrow: 'Contact / collaboration', title: 'A concrete problem worth making simpler?', languages: 'French · English · Wolof' },
    home: { eyebrow: 'Portfolio / Dakar / 2026', title: ['Systems', 'that serve', 'for real.'], bio: 'I design systems that save time, reduce operating costs and turn expertise into durable skills.', primary: 'Explore the proof', secondary: 'Open the lab', availability: 'Available for new projects', languages: 'French · English · Wolof', proofKicker: '02 / what I build', proofTitle: 'Technology becomes useful when it leaves evidence.', proofText: 'Software, automation or training only matters when it removes real friction. Each project connects a field, a constraint and an outcome.', proofLink: 'See the field', experienceKicker: 'Path / field', experienceTitle: 'A method shaped across several systems.', experienceText: 'Delivery, security, development and teaching meet in one path.', labKicker: '04 / intelligence layer', labTitle: 'I do not use AI as a button. I orchestrate it.', labText: 'Context, tools, memory, agents and human validation turn a vague intention into a transferable system.', labCta: 'Enter the lab', skillsKicker: 'Toolbox / skills', skillsTitle: 'A technical foundation, a teaching logic.', skillsText: 'Tools change. The ability to connect them to a need remains.', projectsKicker: '06 / selection', projectsTitle: 'Projects and public proof.', projectsLink: 'See the gallery', metrics: ['observed gain on financial statements', 'AI skills designed and maintained', 'fields: product, infra, AI, teaching'], identity: 'Full-Stack & teaching', labScene: 'Working architecture: context, tools and human validation', labFaces: ['Context', 'Memory', 'Tools', 'Agents', 'Validation', 'Outcome'], labNodes: ['context', 'action', 'continuity'] },
    gallery: { kicker: 'Gallery / field', title: 'The places where the method is built.', text: 'Conferences, workshops, community and teaching from the public historical corpus.', filter: 'Filter the gallery', all: 'All', categories: { Transmission: 'Teaching', Communauté: 'Community', 'Logiciel libre': 'Open source', Projet: 'Project' } },
    tools: { kicker: 'Lab / tools', title: 'Small tools for removing small frictions.', text: 'Three local surfaces that are immediately useful and transparent in how they work.', open: 'Open tool', local: 'local tool', cards: { image: ['WebP Converter', 'Convert an image to WebP in the browser.'], meme: ['Meme Generator', 'Compose a simple visual from local content.'], readme: ['README Generator', 'Quickly structure project documentation.'] } },
    image: { kicker: 'Tool / performance', title: 'Convert an image without leaving the browser.', text: 'Local WebP conversion, with no upload and no intermediary server.', caption: 'Image Converter · project preview', drop: 'Drop an image or browse', convert: 'Convert to WebP', download: 'Download converted.webp' }, meme: { kicker: 'Tool / composition', title: 'One idea, two lines, one visual.', text: 'A small composition surface for prototyping a message and making it shareable.', top: 'Top text', bottom: 'Bottom text', note: 'Local demo: text is rendered in the browser; no file is uploaded.' }, readme: { kicker: 'Tool / teaching', title: 'Give documentation a clear starting point.', text: 'A minimal README, readable and editable through a few fields.', name: 'Project name', description: 'Description', copy: 'Copy README', placeholder: 'Ask about the portfolio…' }, students: { kicker: 'Teaching / pedagogy', title: 'Learn by building something that works.', text: 'Courses grounded in real projects, from the first HTML file to a complete system.', eyebrow: 'A working path', heading: 'Code becomes a skill when you can explain your choices.', body: 'As a PHP, MySQL, HTML, CSS and JavaScript educator, Cherif guides learners through a concrete progression: understand, build, test, teach.', cta: 'Propose a workshop', resources: 'Resources and traces', resourcesText: 'Public projects become reading material: start from a need, follow the decisions, inspect what holds.', resourcesLink: 'See workshop gallery', tracks: [['Frontend', 'HTML, CSS, JavaScript, DOM and responsive design.'], ['Backend', 'PHP, MySQL, Laravel, APIs and MVC architecture.'], ['Method', 'Git, UML, code review, Kanban and documentation.'], ['Applied AI', 'Context, prompts, RAG, agents and responsible automation.']] },
    chat: { assistant: 'Local assistant', title: 'Ask Cherif', available: 'Available', local: 'Local answers', initial: 'Hello. I can guide you through Cherif Diouf’s path and projects.', suggestions: ['Path', 'Public projects', 'Skills', 'Contact'], placeholder: 'Ask about the portfolio…', send: 'Send question', close: 'Close chat', source: 'Public sources used for this answer', sourceProfile: 'Public profile', sourceProjects: 'Public projects', sourceSkills: 'Declared skills', sourceExperience: 'Professional path', sourceTools: 'Local tools' },
  },
  zh: {
    seo: { home: ['Cherif Diouf — 全栈工程师与培训师', 'Cherif Diouf 的作品集：实用系统、自动化、人工智能与知识传承。'], projects: ['项目 — Cherif Diouf', '公开软件、已记录的私有系统与经过验证的演示。'], gallery: ['图库 — Cherif Diouf', '会议、工作坊与知识分享记录。'], tools: ['实验室 — Cherif Diouf', '用于转换、创作和文档整理的本地工具。'], image: ['WebP 转换器 — Cherif Diouf', '在本地将图片转换为 WebP。'], meme: ['表情包生成器 — Cherif Diouf', '用两行文字制作本地视觉内容。'], readme: ['README 生成器 — Cherif Diouf', '为项目文档创建清晰的起点。'], students: ['学生作品 — Cherif Diouf', 'Cherif Diouf 的学生在培训期间制作的五个网页作品集。'] },
    nav: { home: '首页', projects: '项目', gallery: '图库', tools: '工具', students: '学生', contact: '联系' }, footer: { eyebrow: '联系 / 合作', title: '一起把具体问题变简单？', languages: '法语 · 英语 · 沃洛夫语' },
    home: { eyebrow: '作品集 / 达喀尔 / 2026', title: ['让系统', '真正', '服务人。'], bio: '我设计能够节省时间、降低运营成本，并把经验转化为长期能力的系统。', primary: '查看证据', secondary: '进入实验室', availability: '接受新项目', languages: '法语 · 英语 · 沃洛夫语', proofKicker: '02 / 我的构建', proofTitle: '技术只有留下证据，才真正有用。', proofText: '软件、自动化或培训，只有解决真实摩擦才有价值。每个项目都连接一个场景、一项约束和一个结果。', proofLink: '查看现场', experienceKicker: '路径 / 现场', experienceTitle: '在多个系统中形成的方法。', experienceText: '交付、安全、开发与教学汇聚成一条路径。', labKicker: '04 / 智能层', labTitle: '我不把 AI 当作按钮，而是进行编排。', labText: '上下文、工具、记忆、代理与人工验证，把模糊意图变成可传授的系统。', labCta: '进入实验室', skillsKicker: '工具箱 / 技能', skillsTitle: '技术基础与传授逻辑。', skillsText: '工具会变化，把工具连接到需求的能力会留下。', projectsKicker: '06 / 选集', projectsTitle: '项目与公开证据。', projectsLink: '查看图库', metrics: ['财务报表上的已观察收益', '设计并维护的 AI 技能', '领域：产品、基础设施、AI、教学'], identity: '全栈与传授', labScene: '工作架构：上下文、工具与人工验证', labFaces: ['上下文', '记忆', '工具', '代理', '验证', '结果'], labNodes: ['上下文', '行动', '连续性'] },
    gallery: { kicker: '图库 / 现场', title: '方法在这些地方形成。', text: '来自公开历史资料的会议、工作坊、社区与教学记录。', filter: '筛选图库', all: '全部', categories: { Transmission: '传授', Communauté: '社区', 'Logiciel libre': '开源', Projet: '项目' } },
    tools: { kicker: '实验室 / 工具', title: '用小工具消除小摩擦。', text: '三个本地工具，立即可用，并且工作方式清晰可见。', open: '打开工具', local: '本地工具', cards: { image: ['WebP 转换器', '在浏览器中将图片转换为 WebP。'], meme: ['表情包生成器', '使用本地内容组合简单视觉。'], readme: ['README 生成器', '快速整理项目文档。'] } },
    image: { kicker: '工具 / 性能', title: '无需离开浏览器即可转换图片。', text: '本地 WebP 转换，不上传文件，也没有中间服务器。', caption: 'Image Converter · 项目预览', drop: '拖放图片或浏览文件', convert: '转换为 WebP', download: '下载 converted.webp' }, meme: { kicker: '工具 / 创作', title: '一个想法，两行文字，一个视觉。', text: '用一个小型本地界面制作可分享的消息。', top: '顶部文字', bottom: '底部文字', note: '本地演示：文字在浏览器中渲染，不上传文件。' }, readme: { kicker: '工具 / 传授', title: '为文档提供清晰起点。', text: '用几个字段生成可读、可编辑的 README。', name: '项目名称', description: '描述', copy: '复制 README', placeholder: '询问作品集…' }, students: { kicker: '传授 / 教学', title: '通过构建可用的东西来学习。', text: '课程扎根于真实项目，从第一个 HTML 文件到完整系统。', eyebrow: '工作路径', heading: '当你能解释选择时，代码才成为能力。', body: 'Cherif 教授 PHP、MySQL、HTML、CSS 和 JavaScript，以具体进阶陪伴学习者：理解、构建、测试、传授。', cta: '提议工作坊', resources: '资源与记录', resourcesText: '公开项目成为阅读材料：从需求出发，跟随决策，观察系统是否可靠。', resourcesLink: '查看工作坊图库', tracks: [['前端', 'HTML、CSS、JavaScript、DOM 与响应式设计。'], ['后端', 'PHP、MySQL、Laravel、API 与 MVC 架构。'], ['方法', 'Git、UML、代码审查、Kanban 与文档。'], ['应用 AI', '上下文、提示词、RAG、代理与负责任的自动化。']] },
    chat: { assistant: '本地助手', title: '询问 Cherif', available: '在线', local: '本地回答', initial: '你好，我可以介绍 Cherif Diouf 的经历与项目。', suggestions: ['经历', '公开项目', '技能', '联系'], placeholder: '询问作品集…', send: '发送问题', close: '关闭聊天', source: '本回答使用的公开来源', sourceProfile: '公开资料', sourceProjects: '公开项目', sourceSkills: '技能资料', sourceExperience: '职业经历', sourceTools: '本地工具' },
  },
  ja: {
    seo: { home: ['Cherif Diouf — フルスタックエンジニア・講師', '実用的なシステム、自動化、AI、知識共有を扱う Cherif Diouf のポートフォリオ。'], projects: ['プロジェクト — Cherif Diouf', '公開ソフトウェア、構成を公開した非公開システム、検証済みデモ。'], gallery: ['ギャラリー — Cherif Diouf', 'カンファレンス、ワークショップ、知識共有の記録。'], tools: ['ラボ — Cherif Diouf', '変換、制作、ドキュメント化のためのローカルツール。'], image: ['WebP コンバーター — Cherif Diouf', '画像をローカルで WebP に変換します。'], meme: ['ミームジェネレーター — Cherif Diouf', '2行のテキストでローカルなビジュアルを作成します。'], readme: ['README ジェネレーター — Cherif Diouf', 'ドキュメントの明確な出発点を作成します。'], students: ['学生の実績 — Cherif Diouf', 'Cherif Diouf の学生がトレーニング中に制作した5つのウェブポートフォリオ。'] },
    nav: { home: 'ホーム', projects: 'プロジェクト', gallery: 'ギャラリー', tools: 'ツール', students: '学生向け', contact: '連絡先' }, footer: { eyebrow: '連絡 / 協業', title: '具体的な問題をもっと簡単にしませんか？', languages: 'フランス語 · 英語 · ウォロフ語' },
    home: { eyebrow: 'ポートフォリオ / ダカール / 2026', title: ['役に立つ', 'システムを', 'つくる。'], bio: '時間を生み、運用コストを下げ、経験を持続的なスキルへ変えるシステムを設計します。', primary: '証拠を見る', secondary: 'ラボを開く', availability: '新しいプロジェクトに対応', languages: 'フランス語 · 英語 · ウォロフ語', proofKicker: '02 / つくるもの', proofTitle: '技術は証拠を残して初めて役に立つ。', proofText: 'ソフトウェア、自動化、研修は、現実の摩擦を減らしてこそ価値があります。各プロジェクトは現場、制約、結果につながっています。', proofLink: '現場を見る', experienceKicker: '経歴 / 現場', experienceTitle: '複数のシステムで磨いた方法。', experienceText: '安全、開発、教育、納品を一つの道筋に結びます。', labKicker: '04 / インテリジェンス層', labTitle: 'AIをボタンとしてではなく、編成します。', labText: 'コンテキスト、ツール、メモリ、エージェント、人による検証で、曖昧な意図を共有可能なシステムに変えます。', labCta: 'ラボに入る', skillsKicker: 'ツールボックス / スキル', skillsTitle: '技術基盤と伝えるロジック。', skillsText: 'ツールは変わります。必要に結びつける力は残ります。', projectsKicker: '06 / セレクション', projectsTitle: 'プロジェクトと公開された証拠。', projectsLink: 'ギャラリーを見る', metrics: ['財務報告で確認した改善', '設計・維持する AI スキル', '領域：プロダクト、インフラ、AI、教育'], identity: 'フルスタック & 教育', labScene: '仕事の構造：コンテキスト、ツール、人による検証', labFaces: ['コンテキスト', 'メモリ', 'ツール', 'エージェント', '検証', '結果'], labNodes: ['コンテキスト', 'アクション', '継続性'] },
    gallery: { kicker: 'ギャラリー / 現場', title: '方法が育つ場所。', text: '公開された過去の記録から、会議、ワークショップ、コミュニティ、教育を紹介します。', filter: 'ギャラリーを絞り込む', all: 'すべて', categories: { Transmission: '教育', Communauté: 'コミュニティ', 'Logiciel libre': 'オープンソース', Projet: 'プロジェクト' } },
    tools: { kicker: 'ラボ / ツール', title: '小さな摩擦を小さなツールで減らす。', text: 'すぐ使えて、仕組みも読みやすいローカルツールです。', open: 'ツールを開く', local: 'ローカルツール', cards: { image: ['WebP コンバーター', 'ブラウザで画像を WebP に変換します。'], meme: ['ミームジェネレーター', 'ローカル素材から簡単なビジュアルを作ります。'], readme: ['README ジェネレーター', 'プロジェクトのドキュメントをすばやく構成します。'] } },
    image: { kicker: 'ツール / パフォーマンス', title: 'ブラウザを離れずに画像を変換。', text: 'アップロードや中継サーバーなしで、ローカルに WebP へ変換します。', caption: 'Image Converter · プロジェクトプレビュー', drop: '画像をドロップまたは参照', convert: 'WebP に変換', download: 'converted.webp をダウンロード' }, meme: { kicker: 'ツール / 構成', title: 'ひとつのアイデア、2行、ひとつのビジュアル。', text: 'メッセージを試作し、共有できる形にする小さな画面です。', top: '上のテキスト', bottom: '下のテキスト', note: 'ローカルデモ：テキストはブラウザで描画され、ファイルは送信されません。' }, readme: { kicker: 'ツール / 共有', title: 'ドキュメントに明確な出発点を。', text: 'いくつかの項目から読みやすく編集可能な README を作ります。', name: 'プロジェクト名', description: '説明', copy: 'README をコピー', placeholder: 'ポートフォリオについて質問…' }, students: { kicker: '教育 / 学び', title: '動くものを作りながら学ぶ。', text: '最初の HTML ファイルから完全なシステムまで、実際のプロジェクトに基づく講座です。', eyebrow: '仕事の進め方', heading: '選択を説明できて、コードはスキルになる。', body: 'PHP、MySQL、HTML、CSS、JavaScript の講師として、理解、構築、テスト、共有の順に学習を支援します。', cta: 'ワークショップを提案', resources: '資料と記録', resourcesText: '公開プロジェクトを読み物として、課題から決定を追い、何が機能するかを確認します。', resourcesLink: 'ワークショップを見る', tracks: [['フロントエンド', 'HTML、CSS、JavaScript、DOM、レスポンシブデザイン。'], ['バックエンド', 'PHP、MySQL、Laravel、API、MVC アーキテクチャ。'], ['方法', 'Git、UML、コードレビュー、Kanban、ドキュメント。'], ['応用 AI', 'コンテキスト、プロンプト、RAG、エージェント、責任ある自動化。']] },
    chat: { assistant: 'ローカルアシスタント', title: 'Cherif に質問', available: '対応可能', local: 'ローカル回答', initial: 'こんにちは。Cherif Diouf の経歴とプロジェクトをご案内します。', suggestions: ['経歴', '公開プロジェクト', 'スキル', '連絡先'], placeholder: 'ポートフォリオについて質問…', send: '質問を送る', close: 'チャットを閉じる', source: 'この回答に使った公開情報', sourceProfile: '公開プロフィール', sourceProjects: '公開プロジェクト', sourceSkills: '登録スキル', sourceExperience: '職歴', sourceTools: 'ローカルツール' },
  },
} as const;

export function getDictionary(locale: Locale) {
  return dictionaries[locale];
}

export type Dictionary = ReturnType<typeof getDictionary>;
