'use client';
import { useEffect, useState } from 'react';
import { bestMove, createGame, playMove, type GameState, type Player } from '@/lib/tictactoe';
import { tictactoeCopy } from '@/lib/tictactoe-copy';
import type { Locale } from '@/lib/i18n';

export function TicTacToe({ locale }: { locale: Locale }) {
  const copy = tictactoeCopy[locale]; const [human, setHuman] = useState<Player>('X'); const [first, setFirst] = useState<Player>('X');
  const [game, setGame] = useState<GameState>(() => createGame('X')); const [thinking, setThinking] = useState(false); const [score, setScore] = useState({ human: 0, ai: 0, draws: 0 });
  const ai = human === 'X' ? 'O' : 'X'; const begin = (firstPlayer = first) => { setThinking(false); setGame(createGame(firstPlayer)); };
  useEffect(() => { if (game.status !== 'playing' || game.currentPlayer !== ai || thinking) return; const snapshot = game; setThinking(true); const timer = window.setTimeout(() => { const move = bestMove(snapshot.board, ai, snapshot.currentPlayer); setGame((current) => current === snapshot && move !== null ? playMove(current, move) : current); setThinking(false); }, 220); return () => window.clearTimeout(timer); }, [ai, game]);
  useEffect(() => { if (game.status === 'won') setScore((current) => ({ ...current, [game.winner === human ? 'human' : 'ai']: current[game.winner === human ? 'human' : 'ai'] + 1 })); if (game.status === 'draw') setScore((current) => ({ ...current, draws: current.draws + 1 })); }, [game.status, game.winner, human]);
  const status = game.status === 'playing' ? thinking ? copy.thinking : `${copy.turn}: ${game.currentPlayer === human ? copy.human : copy.ai}` : game.status === 'draw' ? copy.draw : game.winner === human ? copy.win : copy.loss;
  return <section className="tictactoe-workbench" aria-label={copy.title}><p className="tic-intro">{copy.text}</p><div className="tic-controls"><fieldset><legend>{copy.symbol}</legend><label><input type="radio" name="tic-symbol" checked={human === 'X'} onChange={() => { setHuman('X'); begin(first); }} /> X</label><label><input type="radio" name="tic-symbol" checked={human === 'O'} onChange={() => { setHuman('O'); begin(first); }} /> O</label></fieldset><fieldset><legend>{copy.first}</legend><label><input type="radio" name="tic-first" checked={first === 'X'} onChange={() => { setFirst('X'); begin('X'); }} /> X</label><label><input type="radio" name="tic-first" checked={first === 'O'} onChange={() => { setFirst('O'); begin('O'); }} /> O</label></fieldset><button className="button button-secondary" type="button" onClick={() => begin()}>{copy.start}</button></div><p className="tic-status" aria-live="polite" aria-atomic="true"><strong>{status}</strong></p><div className="tic-board" role="grid" aria-label={copy.title}>{game.board.map((cell, index) => <button key={index} className={`tic-cell ${cell ? `is-${cell.toLowerCase()}` : ''}`} type="button" role="gridcell" aria-label={`${copy.ariaCell} ${index + 1}${cell ? `: ${cell}` : ''}`} aria-pressed={Boolean(cell)} disabled={Boolean(cell) || game.status !== 'playing' || thinking || game.currentPlayer !== human} onClick={() => setGame((current) => playMove(current, index))}>{cell}</button>)}</div><div className="tic-actions"><button className="button button-primary" type="button" onClick={() => begin()}>{copy.replay}</button><button className="button button-ghost" type="button" onClick={() => { setScore({ human: 0, ai: 0, draws: 0 }); begin(); }}>{copy.reset}</button></div><div className="tic-score" aria-label={copy.score}><span><b>{copy.human}</b><strong>{score.human}</strong></span><span><b>{copy.ai}</b><strong>{score.ai}</strong></span><span><b>{copy.draw}</b><strong>{score.draws}</strong></span></div></section>;
}
