name: Build and Deploy Tailwind CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Déploiement via FTP vers O2Switch

      # Déploiement de tous les fichiers statiques (HTML, JS, CSS, assets) via FTP
      - name: Deploy to O2Switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # On déploie la racine du dépôt (où se trouvent index.html et assets)
          local-dir: .
          server-dir: /home/doya0556/cherif-diouf.artist-dev.com/
          # On ignore les fichiers/dossiers de build et de configuration inutiles sur le serveur
          exclude: |
            node_modules/**
            .github/**
            package.json
            package-lock.json
            tailwind.config.js
            README.md
            CNAME
          dangerous-clean-slate: false
